source 'https://api.berkshelf.com'

cookbook 'apt', '~> 2.6.0'
cookbook 'yum', '~> 3.5.1'
cookbook 'yum-erlang_solutions', '~> 0.2.0'
cookbook 'yum-epel', '~> 0.5.3'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'erlang', '~> 1.5.6'
cookbook 'rabbitmq_settings', '~> 0.1.0'
cookbook 'rabbitmq-management', '~> 0.0.3'
cookbook 'rabbitmq', '~> 3.7.0'
